set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set-option -sg escape-time 10
set-option -g focus-events on
set -s set-clipboard external

setw -g mode-keys vi

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# pane resizing
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g status on
set -g status-interval 60
set -g status-position bottom
set -g status-justify left
set -g status-right-length 100

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

set -g mouse on
# set vi-mode
set-window-option -g mode-keys vi
# keybindings

# Vào copy-mode và bắt đầu chọn bằng phím `v`
bind-key -T copy-mode-vi v send-keys -X begin-selection
# Hủy bỏ việc chọn khi nhấn `Enter`
bind-key -T copy-mode-vi Enter send-keys -X cancel
# Sao chép nội dung được chọn và gửi tới `xclip` để sao chép vào clipboard khi nhấn `y`
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @dracula-plugins "cpu-usage ram-usage time"
set -g @dracula-show-flags true
set -g @dracula-border-contrast true
set -g @dracula-show-empty-plugins false

#powerline
set -g @dracula-show-powerline false
set -g @dracula-show-edge-icons false
set -g @dracula-transparent-powerline-bg true

# left icon
set -g @dracula-show-left-icon "#h|#S "

set -g @dracula-clients-minimum 1
set -g @dracula-git-disable-status true
set -g @dracula-show-timezone true
set -g @dracula-military-time true
set -g @dracula-time-format "%I:%M"
set -g @dracula-ram-usage-label ""
set -g @dracula-cpu-usage-label ""
# default is 1, it can accept any number and 0 disables padding.
set -g @dracula-left-icon-padding 0
# the left separator symbol is inversed with a transparent background, you can modify it with any symbol you like
set -g @dracula-inverse-divider 

# cwd
set -g @dracula-cwd-max-dirs "0"
set -g @dracula-cwd-max-chars "0"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
